# Generated by Django 2.2 on 2021-05-21 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ToDo_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['complete']},
        ),
        migrations.RenameField(
            model_name='task',
            old_name='status',
            new_name='complete',
        ),
    ]
