# Generated by Django 2.2 on 2021-05-22 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ToDo_App', '0004_auto_20210522_0728'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='bill',
            new_name='item',
        ),
    ]
