# Generated by Django 2.2 on 2021-05-23 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ToDo_App', '0004_bill'),
        ('ToDo_App', '0005_auto_20210522_0733'),
    ]

    operations = [
    ]
